name: Add to GitHub Project (Reusable)

on:
  workflow_call:
    inputs:
      project-url:
        required: true
        type: string
    secrets:
      project-token:
        required: true

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add item to GitHub Project (v2)
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: ${{ inputs.project-url }}
          github-token: ${{ secrets.project-token }}
